In [235]:
import scipy.sparse as sps
from logistic_regression import LogisticRegression as LR
data = pd.read_csv('../data/blood.csv', names=['R', 'F', 'M', 'T', 'class'], skiprows=1, dtype=np.float64)
y = data['class'].values
X = data[['R', 'F', 'M', 'T']].values
#X = sps.csr_matrix(X)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [236]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler(with_mean=False)
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [237]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
#lr = LogisticRegression()
lr = LR(learning_rate=1, C=1.0)
mm = MinMaxScaler()
X_train = mm.fit_transform(X_train)
X_test = mm.transform(X_test)
#lr = RandomForestClassifier()

lr.fit(X_train, y_train)
y_p = lr.predict(X_test)
f1_score(y_test, y_p), recall_score(y_test, y_p), precision_score(y_test, y_p)

loss: 0.693147, regu: 0.000000
cost: 0.693147
loss: 0.629151, regu: 0.000062
cost: 0.629214
epoch: 1, cost: 0.629214, diff: 0.063934
loss: 0.596334, regu: 0.000183
cost: 0.596517
epoch: 2, cost: 0.596517, diff: 0.032696
loss: 0.578906, regu: 0.000310
cost: 0.579216
epoch: 3, cost: 0.579216, diff: 0.017301
loss: 0.569254, regu: 0.000425
cost: 0.569679
epoch: 4, cost: 0.569679, diff: 0.009537
loss: 0.563674, regu: 0.000523
cost: 0.564197
epoch: 5, cost: 0.564197, diff: 0.005482
loss: 0.560300, regu: 0.000605
cost: 0.560905
epoch: 6, cost: 0.560905, diff: 0.003293
loss: 0.558157, regu: 0.000672
cost: 0.558829
epoch: 7, cost: 0.558829, diff: 0.002076
loss: 0.556717, regu: 0.000727
cost: 0.557445
epoch: 8, cost: 0.557445, diff: 0.001384
loss: 0.555689, regu: 0.000773
cost: 0.556462
epoch: 9, cost: 0.556462, diff: 0.000982
loss: 0.554906, regu: 0.000811
cost: 0.555717
epoch: 10, cost: 0.555717, diff: 0.000745
loss: 0.554271, regu: 0.000843
cost: 0.555114
epoch: 11, cost: 0.555114, diff: 0.00

(0.125, 0.066666666666666666, 1.0)

In [219]:
lr.w_, lr.b_

(array([[-0.63531155],
        [ 0.37070463],
        [ 0.37070463],
        [-0.46557877]]), -0.53165539915839966)

In [221]:
lr.coef_, lr.intercept_

(array([[-0.63165468,  0.37208158,  0.37208158, -0.46624502]]),
 array([-0.53821782]))

In [180]:
t = lr.predict(X_train)
f1_score(y_train, t), recall_score(y_train, t), precision_score(y_train, t)

(0.0, 0.0, 0.0)

In [233]:
X_train[:, 1].todense()

matrix([[ 0.49887351],
        [ 0.33258234],
        [ 1.1640382 ],
        [ 0.49887351],
        [ 0.83145586],
        [ 0.66516469],
        [ 0.33258234],
        [ 0.16629117],
        [ 0.33258234],
        [ 0.66516469],
        [ 6.81793802],
        [ 0.66516469],
        [ 0.49887351],
        [ 0.33258234],
        [ 0.33258234],
        [ 0.83145586],
        [ 0.66516469],
        [ 0.16629117],
        [ 1.49662054],
        [ 0.66516469],
        [ 0.99774703],
        [ 1.66291171],
        [ 0.16629117],
        [ 0.16629117],
        [ 0.49887351],
        [ 0.49887351],
        [ 1.33032937],
        [ 1.1640382 ],
        [ 0.99774703],
        [ 0.16629117],
        [ 0.49887351],
        [ 0.16629117],
        [ 0.16629117],
        [ 1.66291171],
        [ 0.16629117],
        [ 2.82694991],
        [ 0.16629117],
        [ 0.16629117],
        [ 0.16629117],
        [ 0.33258234],
        [ 0.66516469],
        [ 0.66516469],
        [ 0.16629117],
        [ 0